AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Responder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-responder
      CodeUri: src/responder/
      Handler: bootstrap.is.the.handler
      Runtime: provided.al2
      Architectures:
        - arm64
      MemorySize: 1536
      Timeout: 3
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      BuildMethod: makefile
  ResponderLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Responder}
      RetentionInDays: 14
  DenyListUpdater:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-deny-list-updater
      CodeUri: src/deny_list_updater/
      Handler: bootstrap.is.the.handler
      Runtime: provided.al2
      Architectures:
        - arm64
      MemorySize: 1536
      Timeout: 300
      Environment:
        Variables:
          RESPONDER_FUNCTION_NAME: !Ref Responder
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - lambda:GetFunction
              - lambda:UpdateFunctionCode
            Resource: !GetAtt Responder.Arn
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
    Metadata:
      BuildMethod: makefile
  DenyListUpdaterLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DenyListUpdater}
      RetentionInDays: 14